[package]
name = "status-pages"
version = "0.1.0"
authors = ["Jovin Cronin-Wilesmith <jovin@dave.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.6"
serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0.34"
